openapi: 3.0.0
#servers:
#  - description: Production server
#    url: http://rdarc1.ct.med.ge.com/testrunner
#  - description: Development server
#    url: http://3.57.119.137/testrunner
#  - description: SwaggerHub API Auto Mocking
#    url: http://ctwdof021.am.health.ge.com/virts/212007025/testrunner/1.0.0
    
info:
  description: MindBridge interfaces
  version: "1.0.0"
  title: MindBridge API
  contact:
    email: s.mcolash@ieee.org
  license:
    name: MIT
    url: 'tbd'
    
tags:
  - name: files
    description: Static content
  - name: services
    description: REST service endpoints
    
paths:
  /icon-192.png:
    get:
      tags:
        - files
      summary: application icon
      description: Application icon
      
  /favicon.png:
    get:
      tags:
        - files
      summary: browser icon
      description: Browser icon
      
  /manifest.json:
    get:
      tags:
        - files
      summary: manifest file
      description: Manifest file
      
  /:
    get:
      tags:
        - files
      summary: main page
      description: Main page
      
  /index.html:
    get:
      tags:
        - files
      summary: main page
      description: Main page
      
  /jquery.min.js:
    get:
      tags:
        - files
      summary: jquery library
      description: jquery library
      
  /mindbridge.js:
    get:
      tags:
        - files
      summary: mindbridge library
      description: MindBridge library
      
  /mindbridge.css:
    get:
      tags:
        - files
      summary: mindbridge styles
      description: MindBridge styles
      
  /smpte.gif:
    get:
      tags:
        - files
      summary: SMPTE test pattern
      description: SMPTE test pattern

  /open:
    get:
      tags:
        - services
      summary: request control of the robot
      description: Requst control of the robot.
      responses:
        '200':
          description: status response
          content:
            application/json:
              schema:
                description: status response
                type: object
                items:
                  $ref: '#/components/schemas/StatusResponse'

  /status:
    get:
      tags:
        - services
      summary: get the robot status
      description: Get the robot status.
      responses:
        '200':
          description: status response
          content:
            application/json:
              schema:
                description: status response
                type: object
                items:
                  $ref: '#/components/schemas/StatusResponse'

  /light:
    get:
      tags:
        - services
      summary: control the robot camera LED
      description: Control the robot camera LED.
      responses:
        '200':
          description: status response
          content:
            application/json:
              schema:
                description: status response
                type: object
                items:
                  $ref: '#/components/schemas/StatusResponse'

  /video:
    get:
      tags:
        - services
      summary: produce streaming video
      description: Produce streaming video.
      responses:
        '200':
          description: status response
          content:
            application/json:
              schema:
                description: streaming video
                type: object
                items:
                  $ref: '#/components/schemas/StatusResponse'

/drive:
    get:
      tags:
        - services
      summary: control the robot drives
      description: Control the robot drives.
      responses:
        '200':
          description: status response
          content:
            application/json:
              schema:
                description: status response
                type: object
                items:
                  $ref: '#/components/schemas/StatusResponse'

components:
  schemas:
  
    StatusResponse:
      description: current status
      type: object
      properties:
        VIEW:
          description: the name of the collection
          type: string
          example: "revo_ct.42"

    OpenParameters:
      description: current status
      type: object
      properties:
        VIEW:
          description: the name of the collection
          type: string
          example: "revo_ct.42"

    DriveParameters:
      description: current status
      type: object
      properties:
        VIEW:
          description: the name of the collection
          type: string
          example: "revo_ct.42"
